### ISSUE TITLE
TypeError: cannot unpack non-iterable float object

### ISSUE THREAD

**Issue by fabian-kutschera** [SeismicSource/sourcespec#12]
Hi,

I came across your repository and since I am interested in source spectra I thought I give it a try by following the "Getting started - For the impatient" documentation.

I obtained my data as follows:

- `wget "https://service.iris.edu/fdsnws/event/1/query?starttime=2020-10-30T00:00:00&endtime=2020-10-31T00:00:00&minmag=6&orderby=time&format=xml&nodata=404" -O "event.xml"`
- `wget "https://service.iris.edu/fdsnws/station/1/query?net=II&sta=BFO&starttime=2020-10-30T00:00:00&endtime=2020-10-31T00:00:00&level=response&format=xml&includecomments=true&nodata=404" -O "station.xml"`
- `wget "https://service.iris.edu/fdsnws/dataselect/1/query?net=II&sta=BFO&cha=BH*&starttime=2020-10-30T00:00:00&endtime=2020-10-31T00:00:00&format=miniseed&nodata=404" -O "traces.mseed"`

I generated the config file as described and adjusted the `station_metadata` variable. When I run `source_spec -t traces.mseed -q event.xml` it runs until computing the radiated energy, but then returns the following type error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/import/freenas-m-04-students/fkutschera/miniconda3/envs/python37/bin/source_spec in <module>
      6 if __name__ == '__main__':
      7     sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
----> 8     sys.exit(main())

/import/freenas-m-04-students/fkutschera/miniconda3/envs/python37/lib/python3.7/site-packages/sourcespec/source_spec.py in main()
     72     # Save output
     73     from sourcespec.ssp_output import write_output
---> 74     write_output(config, sourcepar)
     75 
     76     # Save residuals

/import/freenas-m-04-students/fkutschera/miniconda3/envs/python37/lib/python3.7/site-packages/sourcespec/ssp_output.py in write_output(config, sourcepar)
    454     """Write results to a plain text file and/or to a SQLite database file."""
    455     # Write to parfile
--> 456     _write_parfile(config, sourcepar)
    457     # Write to database, if requested
    458     _write_db(config, sourcepar)

/import/freenas-m-04-students/fkutschera/miniconda3/envs/python37/lib/python3.7/site-packages/sourcespec/ssp_output.py in _write_parfile(config, sourcepar)
    243 
    244     Er_mean = means['Er']
--> 245     Er_minus, Er_plus = errors['Er']
    246     # format Er_plus and Er_minus to print it with the same exponent of Er
    247     Er_minus_str = _format_exponent(Er_minus, Er_mean)

**TypeError: cannot unpack non-iterable float object**

I attach the files form the `sspec_out` and would be very happy to get a brief feedback from you. Since I am just getting started I probably did a mistake on the way.

Best regards,
Fabian

[sspec_out.tar.gz](https://github.com/SeismicSource/sourcespec/files/9606014/sspec_out.tar.gz)

**Comment by claudiodsf** [comment]
Dear Fabian,
thanks for your feedback.

What you found is a bug, related to the fact that Er could not be computed for the given station and no other station is available.

I cannot upload to this repository a quick fix for v1.6, since the code has quite evolved and v1.7 will be released soon.

However, you can apply the fix yourself, by replacing `/import/freenas-m-04-students/fkutschera/miniconda3/envs/python37/lib/python3.7/site-packages/sourcespec/ssp_output.py` with the following file (once unzipped).
[ssp_output.py.zip](https://github.com/SeismicSource/sourcespec/files/9608342/ssp_output.py.zip)

Please note that I never tested SourceSpec at regional or teleseismic distances (your station is ~1900 km from the epicentre).
Looking at the trace plot, it seems that the S-window is not correct (and certainly too short, look at `win_length` parameter), and the noise window is probably contaminated by the P arrival and must be shifted earlier (look at `noise_pre_time` parameter).

![11331986 traces](https://user-images.githubusercontent.com/1390993/191280312-ee404229-83c5-4548-acbc-0653596d9395.png)

The obtained spectrum, therefore makes little sense to me:

![11331986 ssp](https://user-images.githubusercontent.com/1390993/191280917-0b934fda-b971-4b70-9a3c-2d4f08bef14b.png)

What is your use case? Are you interested to events at regional distances?

**Comment by claudiodsf** [comment]
This is now fixed in the development version.

**Comment by fabian-kutschera** [comment]
Dear Claudio,
thank you very much for your response and the fix.

I would like to investigate the Mw 7.0 Samos earthquake from October 2020 (https://earthquake.usgs.gov/earthquakes/eventpage/us7000c7y0/executive) and was interested to apply your really nice tool to see, if I could obtain similar earthquake source parameters compared to the proposed ones.

My original choice of a teleseismic recording was probably not a good one, therefore I changed now to a local recording (station HL.ARG..HH* with a distance of 223 km). However, my obtained moment magnitude of 4.5 is still significantly lower than the real earthquake magnitude of Mw7.

So far I rely on the default choice of theoretical picks from the iasp91 model. If I would pick the arrival times by myself using sac, do you think the large discrepancy in moment magnitude could be resolved?

**Comment by claudiodsf** [comment]
Dear Fabian,
It would be useful if you can show me some trace and spectral plots from SourceSpec output.

I just opened the "Discussion" section on this repository (https://github.com/SeismicSource/sourcespec/discussions).

Maybe we can move there:  the discussion can potentially interest other users.

Feel free to open a new discussion and I will reply over there.
