### ISSUE TITLE
Questions about  the config parameters

### ISSUE THREAD

**Issue by wangzb0329** [SeismicSource/sourcespec#8]
Hi,
I have a question about how to determine **the length for S-wave windows and the band-pass frequencies**. These two parameters should be related to the earthquake size and rupture duration, and different settings will lead to significant changes in radiated seismic energy.  Is there a general rule to determine these parameters？
Thank you very much!

**Comment by claudiodsf** [comment]
Hi,
could you please provide an example?

In my tests, the length of the window only marginally affects the parameter estimation, when noise weighting is used (default).

As an example, here are the spectra from the [test IPOC](https://github.com/SeismicSource/sourcespec_testruns/tree/master/test_IPOC) example, using the window length (20 s) and frequency band (0.1-30 Hz) provided for this test:

![073240000HLE ssp_20s](https://user-images.githubusercontent.com/1390993/180029700-449438d7-ec8d-4df3-b107-621fc9d0c575.png)

And here are the spectra obtained doubling the window length (40 s) and enlarging the band to (0.01-30 Hz):

![073240000HLE ssp_40s](https://user-images.githubusercontent.com/1390993/180030029-62171f0a-7d36-4a76-a884-836aed01e542.png)

As you can see, the low-frequency noise below 0.1 Hz is dominant, but the inversion ignores it because of the noise weighting. If you compare the inverted parameters, they are similar, except for PB05.

However, the average parameters are compatible:

parameter | 20 s | 40 s
-- | -- | --
Moment Magnitude | 4.73 ± 0.09 | 4.74 ± 0.09
fc | 3.089 [- 0.820, + 1.116] Hz | 2.704 [- 0.680, + 0.909] Hz
Radiated Energy | 5.961e+12 /- 3.791e+12 /+ 10.411e+12 N.m | 8.171e+12 /- 1.020e+12 /+ 1.165e+12 N.m

Stimulated by your question, I made a small modification in the radiated energy computation by subtracting noise energy from signal energy  ([commit 7a1115e](https://github.com/SeismicSource/sourcespec/commit/7a1115e9a0acc4cd23135a02dd8ec4aff948e916)).
However the improvement is marginal, since noise energy is typically 2-4 order of magnitude smaller than signal energy.

The biggest impact on radiated energy is probably the finite bandwidth correction which depends on the estimation of fc (see equation 4 in [Lancieri et al., 2012](https://doi.org/10.1111/j.1365-246X.2011.05327.x)): increasing fc will increase radiated energy as well.

So maybe, you should check wether your "significant" change in radiated seismic energy is related to a "significant" change in fc estimation.

If you can provide a fully working example, we can see this together 😉.

**Comment by wangzb0329** [comment]
Thank you for your answers.
 
After I checked the papers and my data, I found that the problem might be related to the epicenter distance of the station used. 

The stations used for the determination of the radiated seismic energy should be limited to a distance of 200 km. Because the S wave is dominant at the distance r < 100km and the S wave and surface wave become mixed in the S-wave train at the distancer r ~ 100km, and the surface wave becomes dominant over the entire peak amplitude at r > 200 km (equation 8 in Boatwright et al., 2002).

at distances r > 100 km, waveforms are highly dispersed, with body waves dominating at short periods/high-f (f>2Hz), Lg-waves dominate at intermediate (0.3≤f≤1Hz), and Surface at long period (<0.2Hz). (equation 6 in Boatwright et al., 2002)

It is related to the ‘Geometrical Spreading term’, we use G(r) =r, for r < r0; and G(r)2 =r0r, for r > r0; the stations with distance r > 200 would be discarded. The r0 can be set as 100km. 

Therefore, should r2 in ssp_radiated_energy.py (line42) be considered and take the above part into account?

There is another issue related to the newly added features. 
In computing E, Only the S-wave should be considered when calculating the radiated seismic energy based on the local and regional stations. We should ignore P waves, as they contain only 4% of total seismic energy. 

Thanks

**Comment by claudiodsf** [comment]
Thank you for these insights.

I just added the possibility of choosing the geometrical spreading model via the config parameter `geom_spread_model`.

You can therefore now use the Boatwright et al. (2002) model.
Do you think that it's fine to hardcode the frequency ranges (like in eq 6 of Boatwright)? Or should I add an option for that?

Could you please test this new version and double-check the [source code](https://github.com/SeismicSource/sourcespec/blob/93fda7d1f8bc16fc15c64b7e49acab26c98dd23c/sourcespec/ssp_build_spectra.py#L208) and the [doc](https://sourcespec.readthedocs.io/en/latest/source_spec.html)?

**Comment by claudiodsf** [comment]
> There is another issue related to the newly added features.
> In computing E, Only the S-wave should be considered when calculating the radiated seismic energy based on the local and regional stations. We should ignore P waves, as they contain only 4% of total seismic energy.

I added a warning when radiated energy is computed using P waves: https://github.com/SeismicSource/sourcespec/blob/93fda7d1f8bc16fc15c64b7e49acab26c98dd23c/sourcespec/ssp_radiated_energy.py#L81

**Comment by wangzb0329** [comment]
Thank you for your prompt reply and update, I have tested some events on the new version and it works well. 
Based on the two geometrical spreading models, the average parameters changed slightly for most of the events (Mw4~5), I will test more events with a broad magnitude range in the future.

In my opinion, the frequency ranges can be fixed and may not vary greatly. 

Best regards😁.

**Comment by claudiodsf** [comment]
Great! Don't hesitate to come back here for future inquiries 👍
